### PR TITLE
issue #4 fix

### PR DESCRIPTION
**Pull request by ShibePrime**
Easy fix for #4 

at least for installing anyway 

My initial comit and revert were due to PyCharm going crazy with it's auto formatting tool

### CODE REVIEW

**Review by samclane — CHANGES_REQUESTED** [review]
Thanks for helping out with error finding! I made the change that included the bad indentation using Sublime Text, so that must be why it's inconsistent. 

As for changing the class names, I really like them the way they are (at least for the time being). If you could just include the fixed 'await' statement, I'll go ahead and approve the merge. Thanks again!

**Comment by ShibePrime** [comment]
Waaaa! 
Still getting the hang of how-to github sorry.
Didn't mean to submit any of the additional changes I made. 

(I had another cog using {p}inventory , and was just troubleshooting howto to get this and that to co-exist) 
 
At least you got it going and now I can get everyone in my discord to play with it! 

thanks for a neat cog

**Comment by ShibePrime** [comment]
Forgive my github noobness 
I think I reverted the class name change >_<

**Review by samclane — APPROVED** [review]

**Comment by samclane** [comment]
I tried to merge, but from what I can tell the code is the opposite of what it should be (you undid your fix, and left all the changed class names). 
I can't reopen the issue (or I don't know how, I'm still somewhat new at this haha). If you could just start a new issue with the fixed code I can go ahead and merge.

**Comment by ShibePrime** [comment]
Good to know im not alone at being new too this. 
We'll get it though! I believe :D

**Pull request merged**
